#!/bin/bash

echo "=============== Make dir structure ==============="
mkdir -p ~/tmp
mkdir -p ~/bin
mkdir -p ~/lib
mkdir -p ~/play
mkdir -p ~/utils

echo .
echo "=============== Installing Gitman ==============="
git clone git@github.com:Jodes81/gitman.git ~/utils/gitman
chmod 0755 ~/utils/gitman/setup
~/utils/gitman/setup

#echo .
#echo "=============== Misc Utilities ==============="
git clone git@github.com:Jodes81/runi-tjc-utils-misc.git ~/utils/misc
chmod 0755 ~/utils/misc/setup
~/utils/misc/setup
add-repo ~/utils/misc

#echo .
#echo "=============== WiringPi ==============="
apt-get install make gcc -y
git clone https://github.com/WiringPi/WiringPi.git ~/lib/WiringPi
pushd ~/lib/WiringPi
./build
popd

#echo .
#echo "=============== Auto shutdown ==============="
git clone git@github.com:Jodes81/rpi-autoshutdown.git ~/turtle-pi/autoshutdown
#chmod 0755 ~/turtle-pi/autoshutdown/setup
#~/turtle-pi/autoshutdown/setup
add-repo ~/turtle-pi/autoshutdown

#echo .
#echo "=============== RPi Metrics ==============="
git clone git@github.com:Jodes81/rpi-metrics.git ~/utils/metrics
chmod 0755 ~/utils/metrics/setup
~/utils/metrics/setup
add-repo ~/utils/metrics

#echo .
#echo "=============== Play ==============="
git clone git@github.com:Jodes81/tjc-play.git ~/play/tjc
#chmod 0755 ~/play/tjc/setup
#~/play/tjc/setup
add-repo ~/play/tjc

#echo .
#echo "=============== Node v6.7.0 ==============="
if [ ! $(command -v node) ]; then
  mkdir -p ~/tmp
  pushd ~/tmp
  if [ ! -d node-v6.7.0-linux-armv6l ]; then
    apt-get install xz-utils -y
    if [ ! -f node-v6.7.0-linux-armv6l.tar.xz ]; then
      wget https://nodejs.org/dist/v6.7.0/node-v6.7.0-linux-armv6l.tar.xz
    fi
    tar -xJf node-v6.7.0-linux-armv6l.tar.xz
  fi
  cp -R node-v6.7.0-linux-armv6l/* /usr/local/
  popd
fi

#echo .
#echo "=============== Blockly ==============="
git clone git@github.com:google/blockly.git ~/libs/blockly

