#!/bin/bash

echo "=============== Make dir structure ==============="
mkdir -p ~/tmp
mkdir -p ~/bin
mkdir -p ~/lib
mkdir -p ~/play
mkdir -p ~/utils

echo "=============== Set up paths and preferences ==============="
export PATH="/root/bin:$PATH"
cat <<EOT>> /root/.bashrc
export PATH=/root/bin:$PATH
EOT
cat <<EOT>> /root/.profile
# Not sure what this stuff does, but it's the default in raspbian.
# I just added the setting for stty size
if [ "$BASH" ]; then
  if [ -f ~/.bashrc ]; then
    . ~/.bashrc
  fi
fi

mesg n
stty cols 80 rows 80
EOT

echo .
echo "=============== Installing Gitman ==============="
git clone git@github.com:Jodes81/gitman.git ~/utils/gitman
chmod 0755 ~/utils/gitman/setup
~/utils/gitman/setup

echo .
echo "=============== Register turtle-pi repo with gitman ==============="
add-repo ~/turtle-pi

echo .
echo "=============== Misc Utilities ==============="
git clone git@github.com:Jodes81/runi-tjc-utils-misc.git ~/utils/misc
chmod 0755 ~/utils/misc/setup
~/utils/misc/setup
add-repo ~/utils/misc

echo .
echo "=============== WiringPi ==============="
apt-get install make gcc -y
git clone https://github.com/WiringPi/WiringPi.git ~/lib/WiringPi
pushd ~/lib/WiringPi
./build
popd

echo .
echo "=============== Auto shutdown ==============="
git clone git@github.com:Jodes81/rpi-autoshutdown.git ~/utils/autoshutdown
chmod 0755 ~/utils/autoshutdown/setup
~/utils/autoshutdown/setup
add-repo ~/utils/autoshutdown

echo .
echo "=============== RPi Metrics ==============="
git clone git@github.com:Jodes81/rpi-metrics.git ~/utils/metrics
chmod 0755 ~/utils/metrics/setup
~/utils/metrics/setup
add-repo ~/utils/metrics

echo .
echo "=============== Play ==============="
git clone git@github.com:Jodes81/tjc-play.git ~/play/tjc
#chmod 0755 ~/play/tjc/setup
#~/play/tjc/setup
add-repo ~/play/tjc

echo .
echo "=============== Node v6.7.0 ==============="
if [ ! $(command -v node) ]; then
  mkdir -p ~/tmp
  pushd ~/tmp
  if [ ! -d node-v6.7.0-linux-armv6l ]; then
    apt-get install xz-utils -y
    if [ ! -f node-v6.7.0-linux-armv6l.tar.xz ]; then
      wget https://nodejs.org/dist/v6.7.0/node-v6.7.0-linux-armv6l.tar.xz
    fi
    tar -xJf node-v6.7.0-linux-armv6l.tar.xz
  fi
  cp -R node-v6.7.0-linux-armv6l/* /usr/local/
  popd
fi

echo .
echo "=============== Blockly ==============="
git clone git@github.com:google/blockly.git ~/lib/blockly

