#!/bin/bash

echo .
echo .
echo "======================================="
echo "============= Begin Install ==========="
echo "======================================="
echo .
echo .

echo "=============== Make dir structure ==============="
mkdir -p ~/tmp
mkdir -p ~/bin
mkdir -p ~/lib
mkdir -p ~/play
mkdir -p ~/utils


echo "=============== apt-get update ==============="
apt-get update

echo "=============== Set up paths and preferences ==============="

echo "--- Set up path ---"
export PATH="/root/bin:$PATH"
cat <<EOT>> /root/.bashrc
export PATH=/root/bin:$PATH
EOT

echo "--- Set up console size ---"
cat <<EOT>> /root/.profile
# Not sure what this stuff does, but it's the default in raspbian.
# I just added the setting for stty size
if [ "$BASH" ]; then
  if [ -f ~/.bashrc ]; then
    . ~/.bashrc
  fi
fi

mesg n
stty cols 80 rows 80
EOT

echo "--- Set up binary links ---"
chmod 0755 /root/turtle-pi/turtle-uninstall
chmod 0755 /root/turtle-pi/bin/run-node-server
chmod 0755 /root/turtle-pi/bin/run-video-server
ln -s /root/turtle-pi/bin/run-node-server /root/bin/
ln -s /root/turtle-pi/bin/run-video-server /root/bin/

echo .
echo "=============== Installing Gitman ==============="
git clone git@github.com:Jodes81/gitman.git ~/utils/gitman
chmod 0755 ~/utils/gitman/setup
~/utils/gitman/setup

echo .
echo "----------- Register turtle-pi repo with gitman --------"
add-repo ~/turtle-pi

echo .
echo "=============== Misc Utilities ==============="
git clone git@github.com:Jodes81/runi-tjc-utils-misc.git ~/utils/misc
chmod 0755 ~/utils/misc/setup
~/utils/misc/setup
add-repo ~/utils/misc

echo .
echo "=============== WiringPi ==============="
apt-get install make gcc -y
git clone https://github.com/WiringPi/WiringPi.git ~/lib/WiringPi
pushd ~/lib/WiringPi
./build
popd

echo .
echo "=============== Auto shutdown ==============="
git clone git@github.com:Jodes81/rpi-autoshutdown.git ~/utils/autoshutdown
chmod 0755 ~/utils/autoshutdown/setup
~/utils/autoshutdown/setup
add-repo ~/utils/autoshutdown

echo .
echo "=============== RPi Metrics ==============="
git clone git@github.com:Jodes81/rpi-metrics.git ~/utils/metrics
chmod 0755 ~/utils/metrics/setup
~/utils/metrics/setup
add-repo ~/utils/metrics

echo .
echo "=============== Play ==============="
git clone git@github.com:Jodes81/tjc-play.git ~/play/tjc
#chmod 0755 ~/play/tjc/setup
#~/play/tjc/setup
add-repo ~/play/tjc

echo .
echo "=============== Node v6.7.0 ==============="

apt-get remove nodejs -y

#if [ ! $(command -v node) ]; then
#  mkdir -p ~/tmp
#  pushd ~/tmp
#  if [ ! -d node-v6.7.0-linux-armv6l ]; then
#    apt-get install xz-utils -y
#    if [ ! -f node-v6.7.0-linux-armv6l.tar.xz ]; then
#      wget https://nodejs.org/dist/v6.7.0/node-v6.7.0-linux-armv6l.tar.xz
#    fi
#    tar -xJf node-v6.7.0-linux-armv6l.tar.xz
#  fi
#  cp -R node-v6.7.0-linux-armv6l/* /usr/local/
#  popd
#fi

if [ ! -d /root/lib/node ]; then
  mkdir -p ~/tmp
  pushd ~/tmp
#  if [ ! -d node-v6.7.0-linux-armv6l ]; then
   if [ ! -d node-v7.3.0-linux-armv6l ]; then
    apt-get install xz-utils -y
#    if [ ! -f node-v6.7.0-linux-armv6l.tar.xz ]; then
     if [ ! -f node-v7.3.0-linux-armv6l.tar.xz ]; then
#      wget https://nodejs.org/dist/v6.7.0/node-v6.7.0-linux-armv6l.tar.xz
       wget https://nodejs.org/dist/v7.3.0/node-v7.3.0-linux-armv6l.tar.xz
    fi
#    tar -xJf node-v6.7.0-linux-armv6l.tar.xz
     tar -xJf node-v7.3.0-linux-armv6l.tar.xz
  fi
#  cp -R node-v6.7.0-linux-armv6l /root/lib/node
   cp -R node-v7.3.0-linux-armv6l /root/lib/node
  popd
fi
ln -s /root/lib/node/bin/node /root/bin/node
ln -s /root/lib/node/bin/npm /root/bin/npm



echo .
echo "=============== Blockly ==============="
git clone git@github.com:google/blockly.git ~/lib/blockly --depth 1


# echo .
# echo "=============== Motion ==============="
# apt-get install motion -y
# cp -f /root/turtle-pi/stuff/motion /etc/default/motion
# cp -f /root/turtle-pi/stuff/motion.conf /etc/motion/motion.conf

echo .
echo "=============== MJPG-Streamer ==============="
# https://www.raspberrypi.org/forums/viewtopic.php?p=164539#p164539
# http://unix.stackexchange.com/questions/113893/how-do-i-find-out-which-process-is-using-my-v4l2-webcam
# https://www.raspberrypi.org/forums/viewtopic.php?t=48597
apt-get install libv41 libjpeg8-dev imagemagick -y
git clone git@github.com:jacksonliam/mjpg-streamer.git /root/mjpg-streamer
cd mjpg-streamer/mjpg-streamer-experimental
make USE_LIBV4L2=true clean all
# Not sure the following actually works
make DESTDIR=/usr install

echo .
echo "=============== Install Node Service ==============="
cp /root/turtle-pi/stuff/turtle-node.service /etc/systemd/system/
# systemctl enable turtle-node.service
# systemctl start turtle-node.service
# systemctl status turtle-node.service

echo .
echo "========== Install Video Stream Service =========="
cp /root/turtle-pi/stuff/turtle-video.service /etc/systemd/system/
# systemctl enable turtle-video.service
# systemctl start turtle-video.service
# systemctl status turtle-video.service

# echo .
# echo "========== Install MongoDB =========="
# apt-get install mongodb-server -y
# mkdir -p /data/db

# echo .
# echo "========== Install Strongloop =========="
# npm install -g --save --unsafe-perm strongloop


echo .
echo .
echo "======================================="
echo "=========== Install Complete =========="
echo "======================================="
echo .
echo .
