#!/bin/bash

echo "."
echo "========================================="
echo "=========== Begin Uninstall ============="
echo "========================================="
echo "."

#~/play/tjc/setdown
~/utils/metrics/setdown
~/utils/autoshutdown/setdown
~/utils/misc/setdown
#gitman: nothing to setdown!?
#~/utils/gitman/setdown
	
rm -rf ~/tmp
rm -rf ~/bin
rm -rf ~/lib
rm -rf ~/play
rm -rf ~/utils
rm -rf ~/repos

echo "."
echo "========================================="
echo "========== Uninstall Complete ==========="
echo "========================================="
echo "."



