module.exports = {
    LED_GREEN: 4,
    IR_SENSOR_LEFT: 0,
    IR_SENSOR_RIGHT: 2,
    WHEEL_LEFT_FORWARD: 7,
    WHEEL_LEFT_REVERSE: 6,
    WHEEL_RIGHT_FORWARD: 8,
    WHEEL_RIGHT_REVERSE: 9,
    port: 8080
};

